# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.core.validators import RegexValidator


# Create your models here.
class Member(models.Model):
    firstname = models.CharField(max_length=40, blank=False)
    lastname = models.CharField(max_length=40, blank=False)
    mobile_number = models.CharField(max_length=10, blank=True)
    description = models.TextField(max_length=255, blank=False)
    location = models.TextField(max_length=255, blank=False)
    date = models.DateField('%m/%d/%Y')
    created_at = models.DateTimeField('%m/%d/%Y %H:%M:%S')
    updated_at = models.DateTimeField('%m/%d/%Y %H:%M:%S')

class Document(models.Model):
    description = models.CharField(max_length=255, blank=True)
    document = models.CharField(max_length=255, )
    uploaded_at = models.DateTimeField(auto_now_add=True)

class ContactList(models.Model):
    text = models.CharField(max_length=255, blank=True)
    search = models.CharField(max_length=255)
    email = models.EmailField(max_length=254)
    telephone = models.CharField(max_length=10, blank=True)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()

class CsvUpload(models.Model):
    name = models.CharField(max_length=255, blank=True)
    # description = models.CharField(max_length=255, blank=True)
    end_date = models.DateTimeField()
    # notes = models.CharField(max_length=255, blank=True)
    affectedtoday = models.CharField(max_length=255, blank=True)
    todayRecovered = models.CharField(max_length=255, blank=True)
    todayDeaths = models.CharField(max_length=255, blank=True)
    todayTests = models.CharField(max_length=255, blank=True)
    totalPositive = models.CharField(max_length=255, blank=True)
    totalRecovered = models.CharField(max_length=255, blank=True)
    totalDeaths = models.CharField(max_length=255, blank=True)
    totalTests = models.CharField(max_length=255, blank=True)
    start_date = models.CharField(max_length=255, blank=True)

class CsvUploadFile(models.Model):
    start_date = models.CharField(max_length=255, blank=True)
    Bagerhat = models.CharField(max_length=25, blank=True)
    Bandarban = models.CharField(max_length=25, blank=True)
    Barguna = models.CharField(max_length=25, blank=True)
    Barisal = models.CharField(max_length=25, blank=True)
    Bhola = models.CharField(max_length=25, blank=True)
    Bogra = models.CharField(max_length=25, blank=True)
    Brahmanbaria= models.CharField(max_length=25, blank=True)
    Chandpur= models.CharField(max_length=25, blank=True)
    Chittagong= models.CharField(max_length=25, blank=True)
    Chuadanga= models.CharField(max_length=25, blank=True)
    Comilla= models.CharField(max_length=25, blank=True)
    CoxsBazar= models.CharField(max_length=25, blank=True)
    Dhaka= models.CharField(max_length=25, blank=True)
    Dinajpur= models.CharField(max_length=25, blank=True)
    Faridpur= models.CharField(max_length=25, blank=True)
    Feni= models.CharField(max_length=25, blank=True)
    Gaibandha= models.CharField(max_length=25, blank=True)
    Gazipur= models.CharField(max_length=25, blank=True)
    Gopalganj= models.CharField(max_length=25, blank=True)
    Habiganj= models.CharField(max_length=25, blank=True)
    Jaipurhat= models.CharField(max_length=25, blank=True)
    Jamalpur= models.CharField(max_length=25, blank=True)
    Jessore= models.CharField(max_length=25, blank=True)
    Jhalakati= models.CharField(max_length=25, blank=True)
    Jhenaidah= models.CharField(max_length=25, blank=True)
    Khagrachari= models.CharField(max_length=25, blank=True)
    Khulna= models.CharField(max_length=25, blank=True)
    Kishoreganj= models.CharField(max_length=25, blank=True)
    Kurigram= models.CharField(max_length=25, blank=True)
    Kushtia= models.CharField(max_length=25, blank=True)
    Lakshmipur= models.CharField(max_length=25, blank=True)
    Lalmonirhat= models.CharField(max_length=25, blank=True)
    Madaripur= models.CharField(max_length=25, blank=True)
    Magura= models.CharField(max_length=25, blank=True)
    Manikganj= models.CharField(max_length=25, blank=True)
    Meherpur= models.CharField(max_length=25, blank=True)
    Moulvibazar= models.CharField(max_length=25, blank=True)
    Munshiganj= models.CharField(max_length=25, blank=True)
    Mymensingh= models.CharField(max_length=25, blank=True)
    Naogaon= models.CharField(max_length=25, blank=True)
    Narail= models.CharField(max_length=25, blank=True)
    Narayanganj= models.CharField(max_length=25, blank=True)
    Narsingdi= models.CharField(max_length=25, blank=True)
    Natore= models.CharField(max_length=25, blank=True)
    Nawabganj= models.CharField(max_length=25, blank=True)
    Netrakona= models.CharField(max_length=25, blank=True)
    Nilphamari= models.CharField(max_length=25, blank=True)
    Noakhali= models.CharField(max_length=25, blank=True)
    Pabna= models.CharField(max_length=25, blank=True)
    Panchagarh= models.CharField(max_length=25, blank=True)
    ParbattyaChattagram= models.CharField(max_length=25, blank=True)
    Patuakhali= models.CharField(max_length=25, blank=True)
    Pirojpur= models.CharField(max_length=25, blank=True)
    Rajbari= models.CharField(max_length=25, blank=True)
    Rajshahi= models.CharField(max_length=25, blank=True)
    Rangpur= models.CharField(max_length=25, blank=True)
    Satkhira= models.CharField(max_length=25, blank=True)
    Shariatpur= models.CharField(max_length=25, blank=True)
    Sherpur= models.CharField(max_length=25, blank=True)
    Sirajganj= models.CharField(max_length=25, blank=True)
    Sunamganj= models.CharField(max_length=25, blank=True)
    Sylhet= models.CharField(max_length=25, blank=True)
    Tangail= models.CharField(max_length=25, blank=True)
    Thakurgaon= models.CharField(max_length=25, blank=True)

    SylhetDivision= models.CharField(max_length=25, blank=True)
    RangpurDivision= models.CharField(max_length=25, blank=True)
    RajshahiDivision= models.CharField(max_length=25, blank=True)
    MymensinghDivision= models.CharField(max_length=25, blank=True)
    KhulnaDivision= models.CharField(max_length=25, blank=True)
    DhakaDivision= models.CharField(max_length=25, blank=True)
    ChittagongDivision= models.CharField(max_length=25, blank=True)
    BarisalDivision= models.CharField(max_length=25, blank=True)





