# Generated by Django 3.0.1 on 2020-07-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_member_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvupload',
            name='affectedToday',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
