# Generated by Django 3.0.1 on 2020-07-07 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_csvupload_affectedtoday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvupload',
            old_name='affectedToday',
            new_name='affectedtoday',
        ),
    ]
