# Generated by Django 3.0.1 on 2020-07-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_auto_20200708_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvupload',
            name='todayDeaths',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='csvupload',
            name='todayRecovered',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='csvupload',
            name='todayTests',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='csvupload',
            name='totalDeaths',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='csvupload',
            name='totalPositive',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='csvupload',
            name='totalRecovered',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='csvupload',
            name='totalTests',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
