# Generated by Django 3.0.1 on 2020-07-07 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_auto_20200708_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvupload',
            name='description',
        ),
        migrations.RemoveField(
            model_name='csvupload',
            name='notes',
        ),
    ]
