# Generated by Django 3.0.1 on 2020-07-07 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_auto_20200708_0303'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ajax',
            new_name='ContactList',
        ),
    ]
