# Generated by Django 3.0.1 on 2020-07-11 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_csvuploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvuploadfile',
            name='status_update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
