# Generated by Django 3.0.1 on 2020-07-11 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_csvuploadfile_status_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvuploadfile',
            name='status_update_date',
        ),
    ]
